import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Standard PDF Styles
const styles = StyleSheet.create({
    page: { padding: 40, backgroundColor: '#FFFFFF', color: '#000000', fontFamily: 'Helvetica' },
    header: { marginBottom: 30, borderBottomWidth: 1, borderBottomColor: '#EEEEEE', paddingBottom: 10 },
    title: { fontSize: 24, fontWeight: 'bold', marginBottom: 10 },
    subtitle: { fontSize: 12, color: '#666666', marginBottom: 20 },
    section: { marginBottom: 25 },
    sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#000000', marginBottom: 10, textTransform: 'uppercase' },
    content: { fontSize: 10, lineHeight: 1.6, color: '#333333' },
    grid: { flexDirection: 'row', gap: 20 },
    gridItem: { flex: 1, padding: 10, backgroundColor: '#F9F9F9', borderRadius: 4 },
    label: { fontSize: 8, color: '#999999', marginBottom: 4, textTransform: 'uppercase' },
    value: { fontSize: 12, fontWeight: 'bold' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTopWidth: 1, borderTopColor: '#EEEEEE', paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
    footerText: { fontSize: 8, color: '#999999' }
});

export const AnalysisPDF = ({ data }: { data: any }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Startup Analysis Report</Text>
                <Text style={styles.subtitle}>{data.idea}</Text>
            </View>

            {/* Niche Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>01. Target Niche</Text>
                <Text style={styles.content}>{data.niche.niche_description}</Text>
                <View style={[styles.grid, { marginTop: 15 }]}>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Audience Size</Text>
                        <Text style={styles.value}>{data.niche.audience_size}</Text>
                    </View>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Pain Level</Text>
                        <Text style={styles.value}>{data.niche.pain_level}</Text>
                    </View>
                </View>
            </View>

            {/* Validation */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>02. Market Validation</Text>
                <Text style={styles.content}>{data.validation.key_insight}</Text>
                <View style={[styles.grid, { marginTop: 15 }]}>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>TAM Estimate</Text>
                        <Text style={styles.value}>{data.validation.tam_estimate}</Text>
                    </View>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Verdict</Text>
                        <Text style={styles.value}>{data.validation.validation_verdict.toUpperCase()}</Text>
                    </View>
                </View>
            </View>

            <View style={styles.footer}>
                <Text style={styles.footerText}>Generated by launchOS AI</Text>
                <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
            </View>
        </Page>
    </Document>
);
